### ISSUE TITLE
how change size of icons of windows and size of padding between them 

### ISSUE THREAD

**Issue by hyzyla** [Cobinja/CobiWindowList#10]
Could you describe what lines of code represent the size of the icon on the panel?

**Comment by Cobinja** [comment]
The icon size is 22 px (https://github.com/Cobinja/CobiWindowList/blob/master/windowlist%40cobinja.de/3.2/applet.js#L45), except if the panel option to scale icons and text is enabled.
Then it is panel height * 0.8 (https://github.com/Cobinja/CobiWindowList/blob/master/windowlist%40cobinja.de/3.2/applet.js#L910).
The padding between the buttons is defined by the used theme.

**Comment by Cobinja** [comment]
@hyzyla Can I close this?

**Comment by dhdurgee** [comment]
You indicate that the padding between buttons is defined by the theme.  Could you please clarify where so that I can edit it, as it is a bit wide for me.
