### ISSUE TITLE
Window doesn't appear in window list

### ISSUE THREAD

**Issue by eblis** [Cobinja/CobiWindowList#15]
Terminal windows, setting windows (including CobiWindowList preferences), etc that I open do not appear in my window list unless I first disable "Only show windows on the same monitor" and then re-enable the option.

If I were to keep the option off at all times they would probably appear, but I like seeing only the windows that are on a particular monitor.

This doesn't seem to happen with other window applets, like the default Window list for example.

![image](https://user-images.githubusercontent.com/540188/38141509-20bf23d4-3441-11e8-9d32-b7b8656e091b.png)

**Comment by Cobinja** [comment]
@eblis Does the current master branch fix this for you?

**Comment by eblis** [comment]
Sorry, switched window list applets for a while, just switched back.
Seems to be fixed, thanks.
