### ISSUE TITLE
hover-preview

### ISSUE THREAD

**Issue by hasezoey** [Cobinja/CobiWindowList#17]
Cinnamon 3.6.7
Language: German
(Running in Virtual Box)

(Sorry if this dosnt belong here)
I cant find an option to activate the hover preview
like shown here: https://cinnamon-spices.linuxmint.com/git/applets/windowlist@cobinja.de/screenshot.png

**Comment by Cobinja** [comment]
Hover preview is enabled by default.
You can find it with a right-click on one of the app buttons, then go to "Preferences" and then to "Configure...". This opens the settings dialog. The setting in question is is the "Previews" section and is called "Show on Hover".
This setting, however, is only used if Cinnamon is not in Software Rendering mode.

**Comment by hasezoey** [comment]
Oh Sorry, that i didnt know ... i cant disable software rendering in VB

**Comment by hasezoey** [comment]
Fixed: enabled the 3D acceleration in display settings of the VB
