### ISSUE TITLE
Pinned applications move to other instances of CobiWindowList

### ISSUE THREAD

**Issue by eblis** [Cobinja/CobiWindowList#18]
I have a 3 monitor setup, left monitor -> laptop monitor, middle monitor -> external monitor (primary), right monitor -> external monitor.

I have 3 instances of CobiWindowList, one for each monitor with the following settings:

1. Left monitor
- Caption: Title
- Display caption for: Running
- Group windows: off
- Display favorites: on
- Only show windows on the same monitor: on
- 3 pinned apps

2. Middle monitor
- Caption: Title
- Display caption for: Running
- Group windows: off
- Display favorites: on
- Only show windows on the same monitor: on
- 2 pinned apps

3. Right monitor
- Caption: Title
- Display caption for: Running
- Group windows: off
- Display favorites: off
- Only show windows on the same monitor: on

After my laptop goes to screen saver mode sometimes my pinned apps from Left monitor end up on my Right monitor and vice-versa; the settings seem to move as well.
This could be a problem with Cinnamon or the CobiWindowList, not sure which is to blame.

I've recently updated to Linux Mint 19 with Cinnamon 3.8.7

**Comment by Cobinja** [comment]
I'd say this is an issue with how Cinnamon places applets on the panel, which beyond the applet's control, so closed here.
