### ISSUE TITLE
Can't type text while window preview is showing

### ISSUE THREAD

**Issue by eblis** [Cobinja/CobiWindowList#19]
Not sure if this is a CobiWindowList issue or a Cinnamon 3.8.7 issue, if it's not related to CobiWindowList please close it and I'll raise it with Mint 19 and/or Cinnamon.

Sometimes i select a window and start typing text, but leave my mouse hovering the taskbar and when the window preview for the app I'm currently hovering pops up I can no longer input text in my focused window.

For example I select Slack by clicking on it's application entry in CobiWindowList, then leave the mouse in the same location and start typing. If the window preview popup appears then it steals input and I can no longer type in Slack.

This used to work before updating to Linux Mint 19, Cinnamon 3.8.7 and CobiWindowList, so I'm not sure which one started causing the issue.

**Comment by Cobinja** [comment]
This is due to Cinnamon's system fpr popup menus. While a menu is open, only Cinnamon UI is responsive. There's nothing I can do about it here, so closed.

**Comment by eblis** [comment]
Do you know if this changed recently ? I remember i was able to type even with the preview showing in Linux Mint 18 (and the Cinnamon version it used).

**Comment by eblis** [comment]
Please see this issue raised with Cinnamon, they're saying it's CobiWindowList related https://github.com/linuxmint/Cinnamon/issues/7723

**Comment by mtwebster** [comment]
Maybe hide the popup once/if the window is activated?  That would restore focus, and really you don't need the preview if that window is focused.

edit: I suppose that wouldn't help in all cases, if the pointer lingers over a preview but you don't activate it, just resume typing or whatever.

**Comment by eblis** [comment]
Couldn't the app use tooltips instead of popups, like the stock window list ?

**Comment by Cobinja** [comment]
That wouldn't be feasable because of the missing menu functionality.

**Comment by eblis** [comment]
I deactivated popups on hover but the problem is still there, there's a small popup with the app title that appears and blocks input.

**Comment by sebalis** [comment]
I have had this problem for a long time, at least with Cinnamon 3.6. I don’t think it is due to Cinnamon as another extension I recently switched to, “Window list (Fork by Odyseus)”, did not have this problem. Unfortunately, after a belated update to Cinnamon 3.8, I can’t use that other extension anymore. So I would appreciate if this bug could be reopened and the problem solved.

**Comment by Cobinja** [comment]
The applet you mention also uses tooltips which, as mentioned above, is not feasible here. This stays closed.
