### ISSUE TITLE
Show window preview as a tooltip to allow text input while the preview window is showing

### ISSUE THREAD

**Issue by eblis** [Cobinja/CobiWindowList#20]
I'd like to request a feature where the window preview is shown as a tooltip instead of being shown as a popup, to allow text input while the preview is showing.

Please see https://github.com/Cobinja/CobiWindowList/issues/19

**Comment by Cobinja** [comment]
I will not divide the preview mechanism into menu and tooltip.
However, I introduced a setting that allows you to disable "open on hover" in https://github.com/Cobinja/CobiWindowList/commit/28dd66eb40f972f54bf45765b74e6f77376c7bef
