### ISSUE TITLE
Feature request: make window numbers a bit better

### ISSUE THREAD

**Issue by hasezoey** [Cobinja/CobiWindowList#21]
I have noticed that when only one window is open (of a pinned app) it is not really shown (when "show number" is set to "2 or more")
i would really like it when something like in windows is done (i know it is theme based, but i dont found any theme that would support it)

**Comment by Cobinja** [comment]
I really don't know what you mean. Can be more specific about what you would like to have?

**Comment by hasezoey** [comment]
I mean when you have enabled to show the number only when "2 or more" windows are opened (i have this setting because the number is a bit annoying) i dont see opened windows 
like in this examples:
(Theme Minty)
With Numbers ![](https://gist.githubusercontent.com/hasezoey/09daa3d17f4b5417370aa85e9c3c384d/raw/9a826f47ce9c68296ae6d1b30e08505e4ccb43d8/Minty_with_numbers.PNG)
Without Numbers ![](https://gist.githubusercontent.com/hasezoey/09daa3d17f4b5417370aa85e9c3c384d/raw/9a826f47ce9c68296ae6d1b30e08505e4ccb43d8/Minty_without_numbers.PNG)

(Theme Vivaldi)
With Numbers ![](https://gist.githubusercontent.com/hasezoey/09daa3d17f4b5417370aa85e9c3c384d/raw/9a826f47ce9c68296ae6d1b30e08505e4ccb43d8/Vivaldi_with_number.PNG)
Without Numbers ![](https://gist.githubusercontent.com/hasezoey/09daa3d17f4b5417370aa85e9c3c384d/raw/9a826f47ce9c68296ae6d1b30e08505e4ccb43d8/Vivaldi_without_number.PNG)

and i would like to something like this (Windows): ![](https://gist.githubusercontent.com/hasezoey/09daa3d17f4b5417370aa85e9c3c384d/raw/32cc7b66f2d0026c08beabfb0d0e1eda400d5682/Windows.PNG) 
(That it is opened, without numbers (and eventually when 2 or more like in the explorer), because with only "2 or more" there is only the currently focused window highlighted , ... and i know that the display is theme based)

**Comment by Cobinja** [comment]
Indication of open windows is already supported by my applet, even without numbers.
I tried those themes, not only with my applet, but also with Cinnamon's builtin windowlist applet and Icing Task Manager.
Neither of those applets show such indication with the themes you mentioned.
This is a theming issue, nothing I can fix here, closed.
Btw: Two examples of themes that do support such indication are Mint-Y and the various Mint-X themes

**Comment by hasezoey** [comment]
i thought that it would be a "themeing" issue ... but i didnt found how to change a theme todo that or not even found a theme that would do that / support it ... could you tell how to modify it so that it does it?

**Comment by Cobinja** [comment]
The responsible css class is window-list-item-box

**Comment by Cobinja** [comment]
Sry, that was not meant to happen.
The responsible css class for this window-list-item-box. You can find the installed themes in $HOME/.local/share/themes

**Comment by hasezoey** [comment]
Thanks, [made it](https://github.com/hasezoey/Cinnamon-Vivaldi-Modded) (it took a while, because i dont really know css)

**Comment by Cobinja** [comment]
Just a suggestion: You could turn that into a pull request for the Vivaldi theme, so that other users can use it as well without switching themes
