### ISSUE TITLE
Hard to distinguish open vs pinned closed apps

### ISSUE THREAD

**Issue by mcarans** [Cobinja/CobiWindowList#22]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
2018-05-13
 * Cinnamon version (cinnamon --version)
2.8.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19
 ```
**Issue**
If an application is pinned to the workspace, it is hard to tell if it is open or closed

**Steps to reproduce**
Pin application to workspace - compare open vs closed

**Expected behaviour**
Perhaps the app could be greyed or some other visual effect used to make pinned + closed easily distinguishable from open.

Thanks for a great app. I am trying it after using Icing for a while and other than this issue, it does what I want.

**Comment by Cobinja** [comment]
It's a theming issue. Use a theme that supports it.
See #21, https://github.com/linuxmint/cinnamon-spices-applets/issues/1798
There was an issue which was fixed in https://github.com/Cobinja/CobiWindowList/commit/e5b010e8fe9d3763de06212c47186fe2f1340db3

**Comment by mcarans** [comment]
I am using Mint-Y. 

I can see the numbers but "1" is not that clear merging into the icon for the app. 

The main point though is that I think more than numbers are needed to highlight the distinction.

**Comment by Cobinja** [comment]
I don't think that an applet is the right place for meddling with text theming.

**Comment by mcarans** [comment]
How about adding 0 for no open app windows (ie. closed pinned app)?

**Comment by Cobinja** [comment]
No.
As I said above: There already is a distinction between running and non-running applications (which btw is the same for the builtin window list) !

**Comment by mcarans** [comment]
I'm confused and/or perhaps not explaining myself well. I had a look at the builtin windows list and it has no option to pin applications. A non-running application in the builtin windows list doesn't show at all (which is a clear distinction). 

That distinction doesn't exist with a closed pinned application - if I choose Caption type "Name", Display Caption "All" and Display Number "Never", I cannot see any distinction at all between a closed pinned application and that application with a window open. I am suggesting that there should be some distinction even with Caption type "Name", Display Caption "All" and Display Number "Never". If you are saying there is a distinction, please can you tell me what it is I should be looking for.

**Comment by Cobinja** [comment]
For example try the builtin theme called Cinnamon. Or one of the Mint-X themes.

**Comment by mcarans** [comment]
Now I see it - thanks very much for your help!
