### ISSUE TITLE
Despite existing .desktop files Flatpak apps can not be pinned

### ISSUE THREAD

**Issue by IF-Adin** [Cobinja/CobiWindowList#25]
Hi,

first of all i love your window list applet. And i am fairly certain the problem does not lie with it directly, but i simply can not pin any Flatpak apps to it. I've checked, they all create proper .desktop files and i validated some of them, too, there are no errors.

Any idea what might be causing this? I have the same problem in Gnome, too.

**Comment by IF-Adin** [comment]
Linux Mint 19.1
Cinnamon 4.0.10

**Comment by Cobinja** [comment]
This is nothing I can fix within this applet. But there's a fix for Cinnamon on its way.
https://github.com/linuxmint/cinnamon/pull/8701
