### ISSUE TITLE
Is there a way to show windows label faster ?

### ISSUE THREAD

**Issue by Sh33n** [Cobinja/CobiWindowList#27]
Hello,

It's been a while I'm having issues with Grouped Windows List and I've discovered your applet, thanks a lot for this it works like a charm.

I'd like to know if there is a way to show windows label faster when hoving the mouse over icons ?
It take about 1 second, I'd like it instant if it's possible.

Thank you.

**Comment by Cobinja** [comment]
There are two options for that in the settings menu in the lowest part, "Timeout show" and "Timeout hide", minimum is 5, unit is milliseconds
