### ISSUE TITLE
Numbers are hard to read

### ISSUE THREAD

**Issue by robsdedude** [Cobinja/CobiWindowList#29]
I'm struggling reading the numbers of not focused windows. I'm not sure how this could be fixed. May be by adding theming options or by adding a black border around the numbers.
I've also had a look at the code and tried to implement the border idea but couldn't find an easy way to do it.

Here a little screenshot to demonstrate the issue
![HardToReadNumber](https://user-images.githubusercontent.com/4061254/71542323-4a1be800-2965-11ea-9acd-728ba65e25f5.png)

I mean if you really try hard you can read the 1 but it's merely possible to pick up the numbers when skimming the task bar.

**Comment by Cobinja** [comment]
Please add additional information:

- Which Cinnamon theme are you using?
- What are your panel and panel-icon sizes?

**Comment by robsdedude** [comment]
This is Mint-Y-Dark. I don't know where to find the sizes, however.

**Comment by Cobinja** [comment]
They are in the panel's settings (right click the panel, there's a menu item for them)

**Comment by robsdedude** [comment]
Ah found it. I had it set in theme default (what ever that size is, idk). However, playing around with the size, I couldn't find a setting that would fix the issue.

EDIT: This setting seems to be equivalent to theme default:
![Screenshot from 2020-01-07 13-00-57](https://user-images.githubusercontent.com/4061254/71894169-d5f3f800-314d-11ea-9fb9-b52dd46aee3b.png)

**Comment by robsdedude** [comment]
Thanks for the fix. But I think it didn't change anything for me…

 before ![before](https://user-images.githubusercontent.com/4061254/78870055-cd110c00-7a45-11ea-9b72-3ae6609a7561.png) and after ![after](https://user-images.githubusercontent.com/4061254/78870076-d5694700-7a45-11ea-964b-a5db72d3ca5d.png)


What is it supposed to look like?

**Comment by Cobinja** [comment]
Theme Mint-Y:
![number_badges_01](https://user-images.githubusercontent.com/1781127/78979033-4f1f3480-7b1b-11ea-9b55-2af56b1abcd6.png)
Theme Carta:
![number_badges_02](https://user-images.githubusercontent.com/1781127/78979043-55adac00-7b1b-11ea-8dbe-514c0db49475.png)
Which Cinnamon version do you use? If you're using Cinnamon 3.8 or earlier, you're out of luck. I only support 4.0 and later
And the used theme has to support this as well. This uses CSS classes that are also used by the builtin Grouped Window List.
