### ISSUE TITLE
Some windows don't show up

### ISSUE THREAD

**Issue by Cobinja** [Cobinja/CobiWindowList#3]
@mallardtheduck said on https://cinnamon-spices.linuxmint.com/applets/view/287:
"Some windows don't show up (e.g. Spotify), making them inaccessible if minimised."

I can't reproduce it for Spotify, so I have a couple of questions:
- Which distribution do you use and which version of Cinnamon?
- What are the windows that don't show up for you, other than Spotify?
- Can you supply the contents of
$HOME/.cinnamon/glass.log and
$HOME/.xsession-errors
so that I can take a look at your issue?

**Comment by mbalc** [comment]
I have this issue too

I am using 64bit Linux Mint 18.2, Cinnamon version 3.4.6, fresh install from Mint site
Spotify doesn't show for me, hadn't have any problems yet with other windows but I'm using this applet for about half an hour, not much testing done (I'll update if I encounter other windows as such)

I'm pasting logs below (after opening, closing and opening Spotify)

**Comment by mbalc** [comment]
xsession-errors: 

[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
cinnamon-session[13093]: WARNING: t+2,71739s: Failed to start app: Unable to start application: Failed to execute child process "shutter" (No such file or directory)
Cjs-Message: JS LOG: About to start Cinnamon
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Mon Aug 28 2017 15:44:49 GMT+0200 (CEST)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: JS WARNING: [/home/mbalc/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js 2417]: reference to undefined property this._referralRef
Cjs-Message: JS WARNING: [/home/mbalc/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js 119]: reference to undefined property Settings.BindingDirection.ONE_WAY

(cinnamon:13341): St-WARNING **: Ignoring length property that isn't a number at line 1315, col 11

(cinnamon:13341): St-WARNING **: Ignoring length property that isn't a number at line 1315, col 11
openGL version 3.1 detected (GL3 Cogl Driver)
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: network applet: Found connection for active
Cjs-Message: JS WARNING: [/home/mbalc/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/marknote.js 509]: reference to undefined property elemName.dataType
Cjs-Message: JS WARNING: [/home/mbalc/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/marknote.js 490]: reference to undefined property elemName.dataType

(nvidia-prime:13354): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Cjs-Message: JS WARNING: [/usr/share/cinnamon/js/ui/panel.js 2393]: reference to undefined property this._focusWindow

(cinnamon:13341): Cjs-WARNING **: JS ERROR: TypeError: this._applet is null
CobiAppButton.prototype._onWmClassChanged@/home/mbalc/.local/share/cinnamon/applets/windowlist@cobinja.de/3.2/applet.js:752:5


(cinnamon:13341): Cjs-WARNING **: JS ERROR: TypeError: this._applet is null
CobiAppButton.prototype._onWmClassChanged@/home/mbalc/.local/share/cinnamon/applets/windowlist@cobinja.de/3.2/applet.js:752:5

mintUpdate: no process found
Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x6a00001 (Slack - St)
Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4e0002f (Guake!)

(cinnamon:13341): Cjs-WARNING **: JS ERROR: TypeError: this._applet is null
CobiAppButton.prototype._onWmClassChanged@/home/mbalc/.local/share/cinnamon/applets/windowlist@cobinja.de/3.2/applet.js:752:5


(cinnamon:13341): Cjs-WARNING **: JS ERROR: TypeError: this._applet is null
CobiAppButton.prototype._onWmClassChanged@/home/mbalc/.local/share/cinnamon/applets/windowlist@cobinja.de/3.2/applet.js:752:5


(cinnamon:13341): Cjs-WARNING **: JS ERROR: TypeError: this._applet is null
CobiAppButton.prototype._onWmClassChanged@/home/mbalc/.local/share/cinnamon/applets/windowlist@cobinja.de/3.2/applet.js:752:5


(cinnamon:13341): Cjs-WARNING **: JS ERROR: TypeError: this._applet is null
CobiAppButton.prototype._onWmClassChanged@/home/mbalc/.local/share/cinnamon/applets/windowlist@cobinja.de/3.2/applet.js:752:5

**Comment by mbalc** [comment]
glass.log:

info t=2017-08-28T13:44:48.886Z Cinnamon.AppSystem.get_default() started in 65 ms
info t=2017-08-28T13:44:48.890Z loading user theme: /home/mbalc/.themes/New-Minty/cinnamon/cinnamon.css
info t=2017-08-28T13:44:48.919Z added icon directory: /home/mbalc/.themes/New-Minty/cinnamon
info t=2017-08-28T13:44:49.135Z PlacesManager: Updating devices
info t=2017-08-28T13:44:49.156Z loaded at Mon Aug 28 2017 15:44:49 GMT+0200 (CEST)
info t=2017-08-28T13:44:49.840Z Loaded applet CinnVIIStarkMenu@NikoKrause in 683 ms
info t=2017-08-28T13:44:49.922Z Role locked: panellauncher
info t=2017-08-28T13:44:50.000Z Loaded applet panel-launchers@cinnamon.org in 159 ms
info t=2017-08-28T13:44:50.030Z Loaded applet workspace-switcher@cinnamon.org in 29 ms
info t=2017-08-28T13:44:50.062Z Loaded applet windowlist@cobinja.de in 32 ms
info t=2017-08-28T13:44:50.070Z Loaded applet systray@cinnamon.org in 8 ms
info t=2017-08-28T13:44:50.106Z Loaded applet keyboard@cinnamon.org in 34 ms
info t=2017-08-28T13:44:50.119Z Role locked: notifications
info t=2017-08-28T13:44:50.122Z Loaded applet notifications@cinnamon.org in 15 ms
info t=2017-08-28T13:44:50.137Z Loaded applet removable-drives@cinnamon.org in 13 ms
info t=2017-08-28T13:44:50.173Z Loaded applet user@cinnamon.org in 36 ms
info t=2017-08-28T13:44:50.231Z Loaded applet network@cinnamon.org in 57 ms
info t=2017-08-28T13:44:50.251Z Loaded applet power@cinnamon.org in 18 ms
info t=2017-08-28T13:44:50.293Z Loaded applet calendar@cinnamon.org in 41 ms
info t=2017-08-28T13:44:50.334Z Loaded applet sound@cinnamon.org in 40 ms
info t=2017-08-28T13:44:50.354Z Loaded applet show-desktop@cinnamon.org in 19 ms
info t=2017-08-28T13:44:50.354Z AppletManager.init() started in 1198 ms
info t=2017-08-28T13:44:50.410Z bbcwx (instance 3): refreshing forecast at 15:44:50
info t=2017-08-28T13:44:50.413Z Loaded desklet bbcwx@oak-wood.co.uk in 58 ms
info t=2017-08-28T13:44:50.415Z Cinnamon took 1715 ms to start
info t=2017-08-28T13:44:51.369Z Adding systray: nvidia-prime (24x24px)
info t=2017-08-28T13:44:51.371Z Hiding systray: network
info t=2017-08-28T13:44:52.874Z Resized nvidia-prime with normalized size (16x16px)
info t=2017-08-28T13:44:53.679Z Adding systray: blueberry-tray.py (24x24px)
info t=2017-08-28T13:44:55.181Z Resized blueberry-tray.py with normalized size (16x16px)
info t=2017-08-28T13:45:00.628Z Adding systray: slack (24x24px)
info t=2017-08-28T13:45:02.135Z Resized slack with normalized size (16x16px)
info t=2017-08-28T13:45:09.582Z Adding systray: mintupdate.py (24x24px)
info t=2017-08-28T13:45:11.095Z Resized mintupdate.py with normalized size (16x16px)
info t=2017-08-28T13:45:46.054Z Installing settings for window-list@cinnamon.org
info t=2017-08-28T13:45:46.054Z Settings successfully installed for window-list@cinnamon.org
info t=2017-08-28T13:45:46.082Z Loaded applet window-list@cinnamon.org in 35 ms
info t=2017-08-28T13:45:46.093Z Hiding systray: network
info t=2017-08-28T13:45:46.097Z Adding systray: nvidia-prime (24x24px)
info t=2017-08-28T13:45:46.100Z Adding systray: slack (24x24px)
info t=2017-08-28T13:45:46.104Z Adding systray: blueberry-tray.py (24x24px)
info t=2017-08-28T13:45:46.107Z Adding systray: mintupdate.py (24x24px)
info t=2017-08-28T13:45:47.599Z Resized nvidia-prime with normalized size (16x16px)
info t=2017-08-28T13:45:47.621Z Resized slack with normalized size (16x16px)
info t=2017-08-28T13:45:47.621Z Resized blueberry-tray.py with normalized size (16x16px)
info t=2017-08-28T13:45:47.621Z Resized mintupdate.py with normalized size (16x16px)
info t=2017-08-28T13:45:50.904Z Hiding systray: network
info t=2017-08-28T13:45:50.908Z Adding systray: nvidia-prime (24x24px)
info t=2017-08-28T13:45:50.913Z Adding systray: slack (24x24px)
info t=2017-08-28T13:45:50.917Z Adding systray: blueberry-tray.py (24x24px)
info t=2017-08-28T13:45:50.921Z Adding systray: mintupdate.py (24x24px)
info t=2017-08-28T13:45:52.411Z Resized nvidia-prime with normalized size (16x16px)
info t=2017-08-28T13:45:52.428Z Resized slack with normalized size (16x16px)
info t=2017-08-28T13:45:52.445Z Resized blueberry-tray.py with normalized size (16x16px)
info t=2017-08-28T13:45:52.445Z Resized mintupdate.py with normalized size (16x16px)
info t=2017-08-28T13:47:52.721Z Adding systray: main.py (24x24px)
info t=2017-08-28T13:47:54.223Z Resized main.py with normalized size (16x16px)

**Comment by Cobinja** [comment]
I was able to reproduce this in Mint, but not in Fedora.
Should be fixed in the next version.

**Comment by markkrj** [comment]
I have this issue when opening an LibreOffice document from the nemo file manager. Will it be fixed in the next version as well? If I open an LibreOffice application from the menu, the icon appear normally, but if I open it from nemo, the icon appear while the loading screen is showing, but disappear as soon as it stop loading.

Edit: Just tested the development version and it solved the issue. Is there any known issue with the current development branch or can I use it safely?

**Comment by Cobinja** [comment]
I'd say the git master branch is pretty stable.
I'm working on one more feature, the new version could become published by the end of this week.
