### ISSUE TITLE
Missing theme features with Cobi

### ISSUE THREAD

**Issue by Pandiora** [Cobinja/CobiWindowList#32]
So, since you asked [here](https://github.com/linuxmint/cinnamon/issues/8856#issuecomment-597464614) for opening issues, I'm adding my 2 cents here.

The "working" theme for me is `qob`:
![qob](https://user-images.githubusercontent.com/15093778/76428476-02c2c680-63ae-11ea-9ab3-77242ca5f640.png)

Two other themes (Adapta-Nokto & CBlack) that doesn't work for me as expected:
![Adapta-Nokto](https://user-images.githubusercontent.com/15093778/76428616-30a80b00-63ae-11ea-886e-2a64cbb88bd5.png)

![CBlack](https://user-images.githubusercontent.com/15093778/76428625-34d42880-63ae-11ea-8c82-f0d1528f6692.png)

So what do I expect?
- it should be visible which apps are open (indicator like underline or different background)
- it should be visible which app is currently in the foreground
- it should be visible when I hover an app, but it should be different for those that aren't open
- little manipulations to the theme, like i.e. the padding between icons should be tweakable
(tweaking icon size may not be needed, since imo your icon sizing works well)

Dislaimer:
I'm not sure if the themes itself are not sticking to guidelines and why they're looking so different compared to GWM, I'm just describing what I noticed.

Edit: Looking at CBlack not just the padding between icons should be adjustable but also the padding (or margin) inside each icon container should be equally adjustable.

**Comment by Cobinja** [comment]
CobiWindowList uses the same styles as the builtin standard window list (the one without grouping).
As you can see in your screenshot with qob, there is a distinction between running and non-running apps. That screenshot shows a lighter background for the running terminal and file manager and an even lighter background for cinnamon-settings (which it's the focused app).
The other 2 themes don't seem to have the distinction between running and non-running apps.
I'll think about switching to the styles of the grouped window list.

About padding: I think this should be left completely to themes.

**Comment by Pandiora** [comment]
Okay, maybe I have to give more examples. I now put Cobi and GWM side by side for better comparison (GWM starts with firefox icon):

![qob-bar](https://user-images.githubusercontent.com/15093778/76649700-8244c700-6561-11ea-8c27-da3f91e8090e.png)

For this theme Cobi has the better approach since GWM displays Apps as open (brighter background) which aren't open, like i.e. Firefox.

![adapta-nokto-br](https://user-images.githubusercontent.com/15093778/76649909-d780d880-6561-11ea-89d5-dc1aa87d6c34.png)

For Adapta-Nokto it may be hard to spot but the indicator for open apps is a grey underline and for focused apps a blue underline. All Cobi icons got a grey underlining even if they're not open.

![numix-bar](https://user-images.githubusercontent.com/15093778/76650046-1ca50a80-6562-11ea-856f-b31d3ed8c9ed.png)

And here we got Numix Transparent which confuses me. The styles are completely different and Cobi just shows the style for the focused app.

So my suggestion here would be to make the classes which get applied selectable, since it seems not all theme creators stick to the same guidelines and I really don't want to alter themes. I know GWM or better ITM had this feature before but it got removed somehow. The better approach on the long term surely would be to not have to select any css class.

**Comment by Cobinja** [comment]
I decided against an option because that would be one hell of a code nightmare.

**Comment by Pandiora** [comment]
Okay. Are the styles intended to still look different? (especially Numix and Adapta-Nokto)

**Comment by Cobinja** [comment]
That's probably due to the fact that my applet does not do any widget allocation itself but leaves that all the cinnamon's GUI API. The builtin grouped window list does its own allocation, so e.g. item spacing and size may be different.
Additionally, the changes I made only affect the panel items, not the thumbnails. And before anyone asks: I will not change that.

**Comment by Pandiora** [comment]
I'm not talking about spacing but the styles coming from the themes. Numix Transparent (the third screenshot) visibly got other styles that can only come from the theme itself. So in example classes for states like active, focused, neutral and what not. So either most of the themes are broken or Cobi does something essentially different to GWM.

**Comment by Cobinja** [comment]
I re-checked with adapta-nokto and numix-transparent (as I did before publishing the fix).
I don't see any difference except for spacing.
Can you post new screenshots done with the new version of this applet? And please add a description to them about what exactly the differences are.

**Comment by Pandiora** [comment]
Hey, sorry, I were a little bit busy.

qob: Again apps are getting displayed as "open", which aren't open.
![image](https://user-images.githubusercontent.com/15093778/78333279-d273df80-7589-11ea-9fb0-74e68710e536.png)

Numix Cinnamon Transparent: Almost the same problem as before - css classes getting applied differently or not at all.
![image](https://user-images.githubusercontent.com/15093778/78333368-fe8f6080-7589-11ea-9db9-14c4908b6bb8.png)

Adapta-Nokto: Also the same as before. Closed apps getting displayed as "opened".
![image](https://user-images.githubusercontent.com/15093778/78333495-33031c80-758a-11ea-8b9d-1e0e32232052.png)

**Comment by Cobinja** [comment]
**About qob**
The unwanted styling for non-running windows also happens in the builtin Grouped Window List. It's a theme bug. The latest commit (https://github.com/linuxmint/cinnamon-spices-themes/pull/502/files) inserted this:

> grouped-window-list-item-box {
    color: rgba(255,255,255,1.0);
    background-color: rgba(45,45,45,0.7);
    border-radius: 4px 4px 0px 0px;
    padding: 1px;
    transition-duration: 100;
}

which is the css class used for non-running windows.
So there's no difference between my applet and Grouped Window List.

**About Numix Cinnamon Transparent**
The version on the Spices website (which are used by Cinnamon Settings) does not have any support for the used css classes. Neither has the upstream version at https://github.com/zagortenay333/numix-cinnamon
That's why it does not look different from Grouped Window List. They look equally bad.

**About Adapta-Nokto**
I still cannot reproduce it here. It works just fine (my applet is on the left, Grouped Window List starts with the 2nd Firefox icon):
![Adapta-Nokto](https://user-images.githubusercontent.com/1781127/78982311-2484aa00-7b22-11ea-92a5-bd18546f8797.png)
