### ISSUE TITLE
Align windows on the left side

### ISSUE THREAD

**Issue by nikto1** [Cobinja/CobiWindowList#40]
As per subject, please align the windows on the left side instead of aligning them on the right side.
Each new window is opened on the right side.
As per now it seems RTL instead of LTR (left-to-right).

using linux mint 21.1, seems related to issue #14 with the only difference that on my desktop windows are ALWAYS opened on the right side instead of the left side.

Thanks

**Comment by Cobinja** [comment]
Do you mean they should appear in the left panel zone or do you mean that icons should appear left of the other icons? Can you provide a screenshot that shows what you mean?

**Comment by nikto1** [comment]
The opened windows appear on the left side but they should appear on the right side when opened.
Also when using a program (e.g. notepaddqq, browser, ecc.) it's window move to the right side instead of staying in place.
Please do take note that i've disabled all funky stuff like windows preview, how many windows are opened, grouping windows, ecc
Image:
![screen](https://user-images.githubusercontent.com/9814101/232640838-89331e05-21f7-49ad-85ee-71d339806f17.png)

Thanks!

**Comment by Cobinja** [comment]
Ok, same question again. Left side **of the panel** or to the left **of the other windows**?

**Comment by nikto1** [comment]
As stated windows should appear and stay on the **left side** of the panel and on the **right side when opened**.

![screen](https://user-images.githubusercontent.com/9814101/232841194-addbcda0-49ce-4435-898b-00a489f39070.png)

Take a look how all other program tabs/ windows opens, e.g. notepadqq:
![first](https://user-images.githubusercontent.com/9814101/232843856-d4e3f0f1-bb5a-4707-b3f0-df7de521317f.png)

![test2](https://user-images.githubusercontent.com/9814101/232843889-9ad4768d-92f2-4fa1-a203-a1ac562115b7.png)

![test3](https://user-images.githubusercontent.com/9814101/232843922-3af5d6f8-0b97-49b3-90de-c59eaf57523a.png)


Thanks

**Comment by Cobinja** [comment]
Move the window list to the left panel zone. Right click on the panel, enable "Panel edit mode" and drag'n'drop the window list to the desired zone.
