### ISSUE TITLE
Translated to pt-BR

### ISSUE THREAD

**Issue by ghost** [Cobinja/CobiWindowList#8]
Hi Cobinja, my name is Wolner, and i'm from Brasil.

Thank you a lot to create CobiWindowList.

I maked a .po  and .mo files with the translation to brazilian portuguese.

Please, add it into your applet. So, more people in my country can use CobiWindowList more easly.

Regards,

Wolner Bergamaschine

[pt-BR.zip](https://github.com/Cobinja/CobiWindowList/files/1499689/pt-BR.zip)

**Comment by Cobinja** [comment]
Please create a pull request (either here or in https://github.com/linuxmint/cinnamon-spices-applets)
